# Numpy basic
## Overview
- numpyオンライン試験で

## Sample

### create ndarray

In [8]:
import numpy as np
ary = np.array([5, 8, 3, 4, 2, 0, 8, 3, 7, 0, 4, 0, 0, 2, 5, 7])
ary

array([5, 8, 3, 4, 2, 0, 8, 3, 7, 0, 4, 0, 0, 2, 5, 7])

In [9]:
dir(ary)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [10]:
print(ary)

[5 8 3 4 2 0 8 3 7 0 4 0 0 2 5 7]


In [11]:
ary?

Type:            ndarray
String form:     [5 8 3 4 2 0 8 3 7 0 4 0 0 2 5 7]
Length:          16
File:            g:\users\sakai\anaconda3\envs\jup\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
offset : int, optional
    Offset of array data in buffer.
strides : tuple of ints, optional
    Strides of data in memory.
order : {'C', 'F'}, optional
    Row-major (C-style) or column-major (Fortran-style) order.

Attributes
----------
T : ndarray
    Transpose of the array.
data : buffer
    The array's elements, in memory.
dtype : dtype object
    Describes the format of the elements in the array.
flags : dict
    Dictionary containing information related to memory use, e.g.,
    'C_CONTIGUOUS', 'OWNDATA', 'WRITEABLE', etc.
flat : numpy.flatiter object
    Flattened version of the array as an iterator.  The iterator
    allows assignments, e.g., ``x.flat = 3`` (See `ndarray.flat` for
    assignment examples; TODO).
imag : ndarray
    Imaginary part of the array.
real : ndarray
    Real part of the array.
size : int
    Number of elements in the array.
itemsize : int
    The memory use of each array element in bytes.
nbytes : int
    The total number of bytes required to store the array data,
    i.e., ``itemsize * size``.
ndim : int
    The array's number of dimensions.
shape : tuple of ints
    Shape of the array.
strides : tuple of ints
    The step-size required to move from one element to the next in
    memory. For example, a contiguous ``(3, 4)`` array of type
    ``int16`` in C-order has strides ``(8, 2)``.  This implies that
    to move from element to element in memory requires jumps of 2 bytes.
    To move from row-to-row, one needs to jump 8 bytes at a time
    (``2 * 4``).
ctypes : ctypes object
    Class containing properties of the array needed for interaction
    with ctypes.
base : ndarray
    If the array is a view into another array, that array is its `base`
    (unless that array is also a view).  The `base` array is where the
    array data is actually stored.

See Also
--------
array : Construct an array.
zeros : Create an array, each element of which is zero.
empty : Create an array, but leave its allocated memory unchanged (i.e.,
        it contains "garbage").
dtype : Create a data-type.

Notes
-----
There are two modes of creating an array using ``__new__``:

1. If `buffer` is None, then only `shape`, `dtype`, and `order`
   are used.
2. If `buffer` is an object exposing the buffer interface, then
   all keywords are interpreted.

No ``__init__`` method is needed because the array is fully initialized
after the ``__new__`` method.

Examples
--------
These examples illustrate the low-level `ndarray` constructor.  Refer
to the `See Also` section above for easier ways of constructing an
ndarray.

First mode, `buffer` is None:

>>> np.ndarray(shape=(2,2), dtype=float, order='F')
array([[ -1.13698227e+002,   4.25087011e-303],
       [  2.88528414e-306,   3.27025015e-309]])         #random

Second mode:

>>> np.ndarray((2,), buffer=np.array([1,2,3]),
...            offset=np.int_().itemsize,
...            dtype=int) # offset = 1*itemsize, i.e. skip first element
array([2, 3])

### ndaary.reshape((n,m))

In [12]:
def test1(A):
    retary = A.reshape((4,4))
    return retary

ary1 = test1(ary)
ary1

array([[5, 8, 3, 4],
       [2, 0, 8, 3],
       [7, 0, 4, 0],
       [0, 2, 5, 7]])

In [13]:
ary.shape

(16,)

In [14]:
ary1.shape

(4, 4)

### ndaary.flatten()


In [15]:
def test2(A):
    retary = A.flatten()
    return retary

ary = np.array([[3, 1, 3, 8],
   [0, 5, 1, 2],
   [6, 5, 5, 3]])
ary2 = test2(ary)
ary2

array([3, 1, 3, 8, 0, 5, 1, 2, 6, 5, 5, 3])

In [29]:
ary_s = ary.ravel() 
ary_s

array([3, 1, 3, 8, 0, 5, 1, 2, 6, 5, 5, 3])

### slicing

In [25]:
ary

array([[3, 1, 3, 8],
       [0, 5, 1, 2],
       [6, 5, 5, 3]])

In [22]:
ary[0]

array([3, 1, 3, 8])

In [23]:
ary[0,:]

array([3, 1, 3, 8])

In [26]:
ary[1:,:]

array([[0, 5, 1, 2],
       [6, 5, 5, 3]])

In [28]:
ary[1:2,1:3]

array([[5, 1]])

In [31]:
def test3(A):
    retary = A[2:]
    return retary

ary = np.array([[7, 6, 6, 0, 8, 3],
   [5, 6, 7, 0, 1, 8],
   [3, 8, 3, 7, 6, 6],
   [2, 0, 5, 7, 4, 4],
   [7, 6, 7, 2, 8, 4]])

ary3 = test3(ary)
ary3

array([[3, 8, 3, 7, 6, 6],
       [2, 0, 5, 7, 4, 4],
       [7, 6, 7, 2, 8, 4]])

### np.arange() / np.ramdom

In [34]:
for item in dir(np):
    if not item.startswith('__'):
        print(item)

ALLOW_THREADS
AxisError
BUFSIZE
CLIP
ComplexWarning
DataSource
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
MachAr
ModuleDeprecationWarning
NAN
NINF
NZERO
NaN
PINF
PZERO
PackageLoader
RAISE
RankWarning
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
Tester
TooHardError
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
VisibleDeprecationWarning
WRAP
_NoValue
_distributor_init
_globals
_import_tools
_mat
abs
absolute
absolute_import
add
add_docstring
add_newdoc
add_newdoc_ufunc
add_newdocs
alen
all
allclose
alltrue
amax
amin
angle
any
append
apply_along_axis
apply_over_axes
arange
arccos
arccosh
arcsin
arcsinh
arctan
arctan2
arctanh
argmax
argmin
argpartition
argsort
argwhere
around
array
array2string
array_equal
array_equiv
array_repr
array_split
array_str
asanyarray
asarray
asarray_chkfinite
ascontiguo

In [35]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [36]:
np.random.random((3,3))

array([[0.59671404, 0.80227498, 0.03382778],
       [0.07431366, 0.69201371, 0.36421377],
       [0.63318794, 0.20184109, 0.73416691]])

In [37]:
np.random.rand(3,3)

array([[5.58175768e-01, 7.97874557e-01, 9.20808945e-04],
       [6.21978818e-01, 9.89481850e-01, 2.41924258e-01],
       [1.61443612e-02, 2.14328830e-01, 7.28507936e-03]])

### np.zeros / np.eyes

In [38]:
def test4():
    retary = np.zeros((6,9))
    return retary

ary4 = test4()
ary4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ndarray.T

In [42]:
def test5(A):
    retary = A.T
    return retary

ary = np.array([[6, 0, 5, 8],
   [6, 0, 3, 0],
   [1, 8, 8, 7],
   [0, 1, 7, 0]])
ary5 = test5(ary)
ary5

array([[6, 6, 1, 0],
       [0, 0, 8, 1],
       [5, 3, 8, 7],
       [8, 0, 7, 0]])

### ndarray.hsplit

In [43]:
def test6(A):
    rettpl = np.hsplit(A,3)
    return list(rettpl)

ary = np.array([[7, 6, 8, 7, 9, 7, 7, 6, 5, 6, 7, 2],
   [7, 9, 9, 5, 1, 9, 3, 8, 7, 1, 1, 9],
   [1, 5, 5, 8, 6, 4, 5, 6, 1, 7, 8, 7],
   [3, 8, 3, 9, 9, 3, 9, 2, 6, 1, 7, 1]])

ary6 = test6(ary)
ary6

[array([[7, 6, 8, 7],
        [7, 9, 9, 5],
        [1, 5, 5, 8],
        [3, 8, 3, 9]]), array([[9, 7, 7, 6],
        [1, 9, 3, 8],
        [6, 4, 5, 6],
        [9, 3, 9, 2]]), array([[5, 6, 7, 2],
        [7, 1, 1, 9],
        [1, 7, 8, 7],
        [6, 1, 7, 1]])]

### ndaary.vsplit

In [44]:
def test7(A):
    return list(np.vsplit(A,2))

ary = np.array([[5, 8, 7, 4, 4, 7, 9, 4, 3, 2, 5, 3],
   [2, 9, 9, 8, 5, 3, 8, 9, 3, 6, 9, 1],
   [8, 4, 9, 8, 8, 6, 2, 6, 3, 5, 9, 7],
   [1, 7, 7, 6, 8, 2, 1, 6, 8, 9, 3, 3]])
ary7 = test7(ary)
ary7

[array([[5, 8, 7, 4, 4, 7, 9, 4, 3, 2, 5, 3],
        [2, 9, 9, 8, 5, 3, 8, 9, 3, 6, 9, 1]]),
 array([[8, 4, 9, 8, 8, 6, 2, 6, 3, 5, 9, 7],
        [1, 7, 7, 6, 8, 2, 1, 6, 8, 9, 3, 3]])]

### ndarray.hstack

In [46]:
ary_b = np.array([[1,2,8],[4,5,8]])
ary_c = np.array([[10],[20]])
ary_d = np.concatenate([ary_b,ary_c],axis=1)
ary_d

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])